In [ ]:
import pandas as pd
import yaml
import io
import openpyxl
import csv

In [ ]:
excel_file = 'DV.xlsx'

xl_file = pd.ExcelFile(excel_file)
sheet_names = xl_file.sheet_names
print(f"Các sheet trong file: {sheet_names}")

sheet_list = ['Production, Raw Mat',
'Energy, GHG',
'Water',
'Waste',
'Emission']

for sheet in sheet_names:
    if sheet in sheet_list:
        df = pd.read_excel(excel_file, sheet_name=sheet)
        print(f"Sheet: {sheet}")
        print(f"Kích thước: {df.shape[0]} dòng, {df.shape[1]} cột")
        print(df)
    print("\n")

Các sheet trong file: ['Business', 'Scope', 'Production, Raw Mat', 'Energy, GHG', 'Energy, GHG (2)', 'Water', 'Waste', 'Emission', 'CO2 SAY PHUN']




Sheet: Production, Raw Mat
Kích thước: 20 dòng, 19 cột
                                           Unnamed: 0 Unnamed: 1 Unnamed: 2  \
0                    Production (DV Tile + YB Powder)       unit        Jan
1                  Production (DV Tile) (Sản phẩm ĐV)        ton   9609.931
2       Production (YB Powder) (bột bán cho Yên Bình)        ton          0
3                          Total Production (DV + YB)        ton   9609.931
4                                                 NaN        NaN        NaN
5                                        Raw Material       unit        Jan
6                          Limestone/ Đá vôi (canxit)        ton    1185.21
7                                       Clay/ Đất sét        ton    6280.95
8                                           Sand/ Cát        ton        NaN
9                                   Gypsum/ Thạch cao        ton        NaN
10                                   Laterite/ Đá ong        ton        NaN
11                                    Cement/ Xi măng        ton        NaN
12                                           Feldspar        ton     696.15
13                             Aggregate/ Chất kết tụ        ton        NaN
14                                      Pottery Stone        ton        NaN
15                  Glazing (Men ướt nhập VP quy khô)        ton     611.66
16  Recycled Mat/ Nguyên liệu tái sử dụng (gạch tá...        ton     625.13
17                           Others/ Nguyên liệu khác        ton        NaN
18              Total raw materials/ Tổng nguyên liệu        ton     9399.1
19                        % Alternative raw materials          %    0.06651

     Unnamed: 3   Unnamed: 4   Unnamed: 5   Unnamed: 6   Unnamed: 7  \
0           Feb          Mar          Apr          May          Jun
1   6310.080933  17732.97347  15795.45537  16091.79977  16408.01583
2             0            0            0            0          NaN
3   6310.080933  17732.97347  15795.45537  16091.79977  16408.01583
4           NaN          NaN          NaN          NaN          NaN
5           Feb          Mar          Apr          May          Jun
6        903.63     2451.735     2133.495      2066.22     2160.795
7        4812.6     13112.58     11433.24    11029.452     11323.65
8           NaN          NaN          NaN          NaN          NaN
9           NaN          NaN          NaN          NaN          NaN
10          NaN          NaN          NaN          NaN          NaN
11          NaN          NaN          NaN          NaN          NaN
12        772.2       1762.8      1414.14     1600.308      1814.67
13          NaN          NaN          NaN          NaN          NaN
14          NaN          NaN          NaN          NaN          NaN
15      593.122     1366.899     1232.648     1224.313     1274.894
16       364.14      1105.56       1051.7       989.61      1257.75
17          NaN          NaN          NaN          NaN          NaN
18     7445.692    19799.574    17265.223    16909.903    17831.759
19     0.048906     0.055838     0.060914     0.058523     0.070534

    Unnamed: 8   Unnamed: 9  Unnamed: 10  Unnamed: 11  Unnamed: 12  \
0          Jul          Aug          Sep          Oct          Nov
1   18454.3238  16179.63025  12136.76037  12464.84122  12324.14555
2          NaN          NaN          NaN          NaN          NaN
3   18454.3238  16179.63025  12136.76037  12464.84122  12324.14555
4          NaN          NaN          NaN          NaN          NaN
5          Jul          Aug          Sep          Oct          Nov
6     2501.265      2094.69      1523.34     1624.155      1624.35
7    13526.175    12506.465      8783.97      9729.72     9687.405
8          NaN          NaN          NaN          NaN          NaN
9          NaN          NaN          NaN          NaN          NaN
10         NaN          NaN          NaN          NaN          NaN
11         NaN          NaN          NaN          NaN          NaN
12     2458.17        963.3       958.62        877.5        627.9
13         NaN          NaN          NaN          NaN          NaN
14         NaN          NaN          NaN          NaN          NaN
15    1532.653     1223.418      908.336      1025.46      906.515
16     1428.32     1273.535      917.475       881.01       917.28
17         NaN          NaN          NaN          NaN          NaN
18   21446.583    18061.408    13091.741    14137.845     13763.45
19    0.066599     0.070511      0.07008     0.062316     0.066646

    Unnamed: 13  Unnamed: 14 Unnamed: 15  Unnamed: 16  Unnamed: 17  \
0           Dec          YTD          Q1           Q2           Q3
1   15580.26882  169088.2264  33652.9854  48295.27097  46770.71442
2      423.6674     423.6674           0            0            0
3   16003.93622  169511.8938  33652.9854  48295.27097  46770.71442
4           NaN          NaN         NaN          NaN          NaN
5           Dec          YTD          Q1           Q2           Q3
6       1872.75    22141.635    4540.575      6360.51     6119.295
7     11518.615   123744.822    24206.13    33786.342     34816.61
8           NaN            0           0            0            0
9           NaN            0           0            0            0
10          NaN            0           0            0            0
11          NaN            0           0            0            0
12       1141.7    15087.458     3231.15     4829.118      4380.09
13          NaN            0           0            0            0
14          NaN            0           0            0            0
15     1268.747    13168.665    2571.681     3731.855     3664.407
16      1021.98     11833.49     2094.83      3299.06      3619.33
17          NaN            0           0            0            0
18    16823.792    185976.07   36644.366    52006.885    52599.732
19     0.060746     0.063629    0.057166     0.063435     0.068809

    Unnamed: 18
0            Q4
1   40369.25559
2      423.6674
3   40792.92299
4           NaN
5            Q4
6      5121.255
7      30935.74
8             0
9             0
10            0
11            0
12       2647.1
13            0
14            0
15     3200.722
16      2820.27
17            0
18    44725.087
19     0.063058


Sheet: Energy, GHG
Kích thước: 132 dòng, 22 cột
                                       Unnamed: 0      Unnamed: 1 Unnamed: 2  \
0                              Energy Consumption            unit        Jan
1                              Coal/ Than 5A (DV)             Ton   1233.522
2                            Coal/ Than 4A.1 (DV)             Ton        443
3    Coal/ Than import coal (DV) (than nhập khẩu)             Ton          0
4     Than cám qua sàng / Than 5A under screen DV             Ton        114
..                                            ...             ...        ...
127                                         Steam  Local Currency        NaN
128              Solid Biomass (Renewable Energy)  Local Currency        NaN
129                                   Electricity         Ringgit        NaN
130                         Co-generation (Power)  Local Currency        NaN
131                 Solar Cell (Renewable Energy)  Local Currency        NaN

    Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6 Unnamed: 7 Unnamed: 8  \
0          Feb        Mar        Apr        May        Jun        Jul
1          983   2414.661   2198.795   2197.301    2170.99   2442.916
2       251.25    543.069     88.335     774.19    319.418     508.88
3        92.48    430.117    722.734          0     434.63     375.27
4           88    206.339    209.205    204.699     201.01    188.848
..         ...        ...        ...        ...        ...        ...
127        NaN        NaN        NaN        NaN        NaN        NaN
128        NaN        NaN        NaN        NaN        NaN        NaN
129        NaN        NaN        NaN        NaN        NaN        NaN
130        NaN        NaN        NaN        NaN        NaN        NaN
131        NaN        NaN        NaN        NaN        NaN        NaN

    Unnamed: 9  ... Unnamed: 12 Unnamed: 13 Unnamed: 14 Unnamed: 15  \
0          Aug  ...         Nov         Dec         YTD          Q1
1     2148.882  ...      1649.3    2061.215         NaN    4631.183
2      630.609  ...      113.76     369.092         NaN    1237.319
3        77.21  ...     352.255     533.023         NaN     522.597
4      204.034  ...       156.7     175.785         NaN     408.339
..         ...  ...         ...         ...         ...         ...
127        NaN  ...         NaN         NaN         NaN         NaN
128        NaN  ...         NaN         NaN         NaN         NaN
129        NaN  ...         NaN         NaN         NaN         NaN
130        NaN  ...         NaN         NaN         NaN         NaN
131        NaN  ...         NaN         NaN         NaN         NaN

    Unnamed: 16 Unnamed: 17 Unnamed: 18 Unnamed: 19 Unnamed: 20 Unnamed: 21
0            Q2          Q3          Q4         NaN         NaN         NaN
1      6567.086    6310.711     5464.47         NaN         NaN         NaN
2      1181.943    1584.048     501.752         NaN         NaN         NaN
3      1157.364      452.48    1436.158         NaN         NaN         NaN
4       614.914     526.657      485.53         NaN         NaN         NaN
..          ...         ...         ...         ...         ...         ...
127         NaN         NaN         NaN         NaN         NaN         NaN
128         NaN         NaN         NaN         NaN         NaN         NaN
129         NaN         NaN         NaN         NaN         NaN         NaN
130         NaN         NaN         NaN         NaN         NaN         NaN
131         NaN         NaN         NaN         NaN         NaN         NaN

[132 rows x 22 columns]




Sheet: Water
Kích thước: 21 dòng, 19 cột
                                      Unnamed: 0 Unnamed: 1  \
0                               Water Withdrawal       unit
1           Surface water (Lake) (DV) (Nước mặt)         m3
2           Surface water (Lake) (YB) (Nước Mặt)         m3
3   Surface water (Lake) (DV+YB) (tổng nước mặt)         m3
4                      Ground water (wells) (DV)         m3
5                      Tap wate (DV) (Nước sạch)         m3
6                    Total Water Withdrawal (DV)         m3
7                    Total Water Withdrawal (YB)         m3
8                 Total Water Withdrawal (DV+YB)         m3
9                 Specific Water Withdrawal (DV)     m3/ton
10                Specific Water Withdrawal (YB)     m3/ton
11             Specific Water Withdrawal (DV+YB)     m3/ton
12                                           NaN        NaN
13                                 Water Recycle       unit
14               Water Recycle/ Nước tái sử dụng         m3
15                                           NaN        NaN
16                               Ko có nước ngầm        NaN
17                                           NaN        NaN
18                               Ko có nước ngầm        NaN
19                                           NaN        NaN
20                                           NaN        NaN

                         Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5  \
0                               Jan        Feb        Mar        Apr
1                              4987       3058       6675       6392
2                                 0          0          0          0
3                              4987       3058       6675       6392
4                                 0          0          0          0
5                               658       1198       1079       1292
6                              5645       4256       7754       7684
7                                 0          0          0          0
8                              5645       4256       7754       7684
9                          0.587413   0.674476   0.437265   0.486469
10                          #DIV/0!    #DIV/0!    #DIV/0!    #DIV/0!
11                         0.587413   0.674476   0.437265   0.486469
12                              NaN        NaN        NaN        NaN
13                              Jan        Feb        Mar        Apr
14                             3047       2139       5669       5231
15                              NaN        NaN        NaN        NaN
16                              NaN        NaN        NaN        NaN
17                              NaN        NaN        NaN        NaN
18                              NaN        Jan        Feb        Mar
19           Total Water Withdrawal      12839       6903       9043
20  Water Recycle/ Nước tái sử dụng       4254       1350       4198

   Unnamed: 6 Unnamed: 7 Unnamed: 8 Unnamed: 9 Unnamed: 10 Unnamed: 11  \
0         May        Jun        Jul        Aug         Sep         Oct
1        6393       6254       6934       6241        5438        6081
2           0          0          0          0           0           0
3        6393       6254       6934       6241        5438        6081
4           0          0          0          0         NaN         NaN
5         631       1524       2083       1586        1369        1289
6        7024       7778       9017       7827        6807        7370
7           0          0          0          0           0           0
8        7024       7778       9017       7827        6807        7370
9    0.436496   0.474037   0.488612   0.483756    0.560858    0.591263
10    #DIV/0!    #DIV/0!    #DIV/0!    #DIV/0!     #DIV/0!     #DIV/0!
11   0.436496   0.474037   0.488612   0.483756    0.560858    0.591263
12        NaN        NaN        NaN        NaN         NaN         NaN
13        May        Jun        Jul        Aug         Sep         Oct
14       4453       4245       6172       5372        4704        4552
15        NaN        NaN        NaN        NaN         NaN         NaN
16        NaN        NaN        NaN        NaN         NaN         NaN
17        NaN        NaN        NaN        NaN         NaN         NaN
18        Apr        May        Jun        Jul         Aug         Sep
19      11134      14106      13676      13709       12091       12437
20       4986       5449       4655       4177        5816        5681

   Unnamed: 12 Unnamed: 13 Unnamed: 14 Unnamed: 15 Unnamed: 16 Unnamed: 17  \
0          Nov         Dec         YTD          Q1          Q2          Q3
1         6741        7894       73088       14720       19039       18613
2            0           0           0           0           0           0
3         6741        7894       73088       14720       19039       18613
4          NaN         NaN           0           0           0           0
5         1726        1064       15499        2935        3447        5038
6         8467        8958       88587       17655       22486       23651
7            0           0           0           0           0           0
8         8467        8958       88587       17655       22486       23651
9     0.687025    0.574958     #ERROR!     #ERROR!     #ERROR!     #ERROR!
10     #DIV/0!           0           0     #DIV/0!     #DIV/0!     #DIV/0!
11    0.687025    0.559737      0.5226    0.524619    0.465594     0.50568
12         NaN         NaN         NaN         NaN         NaN         NaN
13         Nov         Dec         YTD          Q1          Q2          Q3
14        5187        5392         NaN       10855       13929       16248
15         NaN         NaN         NaN         NaN         NaN         NaN
16         NaN         NaN         NaN         NaN         NaN         NaN
17         NaN         NaN         NaN         NaN         NaN         NaN
18         Oct         Nov         Dec         NaN         NaN         NaN
19       10166       12485           0         NaN         NaN         NaN
20        5544        4951         NaN         NaN         NaN         NaN

   Unnamed: 18
0           Q4
1        20716
2            0
3        20716
4            0
5         4079
6        24795
7            0
8        24795
9      #ERROR!
10           0
11    0.607826
12         NaN
13          Q4
14       15131
15         NaN
16         NaN
17         NaN
18         NaN
19         NaN
20         NaN


Sheet: Waste
Kích thước: 30 dòng, 67 cột
                                           Unnamed: 0  \
0           Hazardous Waste (ton)/ CHẤT THẢI NGUY HẠI
1                                                 NaN
2                                                 NaN
3   Contaminated Cloth/ Bao gồm giẻ lau, gang tay ...
4   Used oil/ Tất cả các loại dầu đã qua sử dụng thải
5   Package contaminated / Vỏ thùng sơn, vỏ thùng ...
6   Electronic equipment / Các thiết bị điện thải ...
7   Insulation/ Vật liệu cách nhiệt (amiăng thải, ...
8                                   Đất dính hóa chất
9                      Cặn rắn từ quá trình sử lý men
10                                  Nước rửa băng tải
11                                                NaN
12               Total Hazardous Waste Generate (ton)
13         Specific Hazardous Waste Generate (kg/ton)
14                                                NaN
15  Non Hazardous Waste (ton)/ CHẤT THẢI THÔNG THƯỜNG
16                                                NaN
17                                                NaN
18  Tiles after kiln, coal slag/ Gạch sau nung, sỉ...
19                                        Sludge/ Bùn
20  Paper packaging/ Giấy bao bì, các loại giấy bỏ...
21  Plastic packaging, (Wrap, Bigbag)/ Nhựa bao gồ...
22                  Wooden Packaging (Pallet, gỗ củi)
23  Rubber/ Cao su (bao gồm các loại dây cao su, d...
24  Refractory/ Gạch chịu lửa (Gạch lò tầng sôi,\n...
25           Other (Dây dù, Túi lọc bụi (filter bag))
26                          iron waste (Sắt phế liệu)
27                                       Con lăn hỏng
28           Total Non Hazardous Waste Generate (ton)
29     Specific Non Hazardous Waste Generate (kg/ton)

                 Unnamed: 1                            Unnamed: 2  \
0                       Jan                                   NaN
1   Incoming Stock/ Tồn đầu  Waste generated/ Chất thải phát sinh
2                       NaN                                   NaN
3                    0.3472                                  0.03
4                    5.8526                                     0
5                     2.413                                0.1281
6                    0.1484                                 0.013
7                    1.6998                                 0.029
8                    0.2316                                     0
9                      0.04                                     0
10                      NaN                                     0
11                        0                                   NaN
12                  10.7326                                0.2001
13                      NaN                              0.020822
14                      NaN                                   NaN
15                      Jan                                   NaN
16  Incoming Stock/ Tồn đầu  Waste generated/ Chất thải phát sinh
17                      NaN                                   NaN
18                        0                                 68.78
19                        0                                     0
20                        0                                  1.92
21                        0                                  0.58
22                        0                                     0
23                    4.069                                  0.05
24                        0                                     0
25                   1.8301                                     0
26                        0                                 28.28

Energy, GHG

In [ ]:
# sheet 'Energy, GHG'
df_energy = pd.read_excel(excel_file, sheet_name='Energy, GHG')
print(df_energy.head(10))

                                     Unnamed: 0 Unnamed: 1 Unnamed: 2  \
0                            Energy Consumption       unit        Jan
1                            Coal/ Than 5A (DV)        Ton   1233.522
2                          Coal/ Than 4A.1 (DV)        Ton        443
3  Coal/ Than import coal (DV) (than nhập khẩu)        Ton          0
4   Than cám qua sàng / Than 5A under screen DV        Ton        114
5                            Coal/ Than 5A (YB)        Ton          0
6                          Coal/ Than 4A.1 (YB)        Ton          0
7  Coal/ Than import coal (YB) (than nhập khẩu)        Ton          0
8   Than cám qua sàng / Than 5A under screen YB        Ton          0
9                         Coal/ Than 5A (DV+YB)        Ton   1233.522

  Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6 Unnamed: 7 Unnamed: 8  \
0        Feb        Mar        Apr        May        Jun        Jul
1        983   2414.661   2198.795   2197.301    2170.99   2442.916
2     251.25    543.069     88.335     774.19    319.418     508.88
3      92.48    430.117    722.734          0     434.63     375.27
4         88    206.339    209.205    204.699     201.01    188.848
5          0          0        NaN        NaN        NaN        NaN
6          0          0        NaN        NaN        NaN        NaN
7          0          0        NaN        NaN        NaN        NaN
8          0          0        NaN        NaN        NaN        NaN
9        983   2414.661   2198.795   2197.301    2170.99   2442.916

  Unnamed: 9  ... Unnamed: 12 Unnamed: 13 Unnamed: 14 Unnamed: 15 Unnamed: 16  \
0        Aug  ...         Nov         Dec         YTD          Q1          Q2
1   2148.882  ...      1649.3    2061.215         NaN    4631.183    6567.086
2    630.609  ...      113.76     369.092         NaN    1237.319    1181.943
3      77.21  ...     352.255     533.023         NaN     522.597    1157.364
4    204.034  ...       156.7     175.785         NaN     408.339     614.914
5        NaN  ...         NaN         NaN         NaN           0           0
6        NaN  ...         NaN   27.623114         NaN           0           0
7        NaN  ...         NaN         NaN         NaN           0           0
8        NaN  ...         NaN         NaN         NaN           0           0
9   2148.882  ...      1649.3    2061.215           0    4631.183    6567.086

  Unnamed: 17 Unnamed: 18 Unnamed: 19 Unnamed: 20 Unnamed: 21
0          Q3          Q4         NaN         NaN         NaN
1    6310.711     5464.47         NaN         NaN         NaN
2    1584.048     501.752         NaN         NaN         NaN
3      452.48    1436.158         NaN         NaN         NaN
4     526.657      485.53         NaN         NaN         NaN
5           0           0         NaN         NaN         NaN
6           0   27.623114         NaN         NaN         NaN
7           0           0         NaN         NaN         NaN
8           0           0         NaN         NaN         NaN
9    6310.711     5464.47         NaN         NaN         NaN

[10 rows x 22 columns]

In [ ]:
def find_sections(df, section_names):
    section_markers = {}
    for idx, row in df.iterrows():
        row_str = str(row.iloc[0]).strip() if pd.notna(row.iloc[0]) else ''
        for name in section_names:
            if row_str == name:
                section_markers[name] = idx
    return section_markers

In [ ]:
energy_df = df_energy.reset_index(drop=True)

section_names = ['Energy Consumption', 'Greenhouse Gas Emission', 'Conversion Factor', 'Energy Cost']
section_markers = find_sections(energy_df, section_names)

sorted_sections = sorted([(idx, s) for s, idx in section_markers.items() if idx is not None])

for i, (start_idx, section) in enumerate(sorted_sections):
    end_idx = sorted_sections[i + 1][0] if i < len(sorted_sections) - 1 else len(energy_df)
    df_part = energy_df.iloc[start_idx:end_idx].copy()
    df_part_clean = pd.DataFrame(df_part.iloc[1:].values, columns=df_part.iloc[0])
    print(section)
    print(len(df_part_clean), "hàng x", len(df_part_clean.columns), "cột")
    print(df_part_clean.head(10).to_string())

Energy Consumption
65 hàng x 22 cột
0                            Energy Consumption unit       Jan     Feb       Mar       Apr       May      Jun       Jul       Aug       Sep       Oct      Nov         Dec  YTD        Q1        Q2        Q3          Q4  NaN  NaN  NaN
0                            Coal/ Than 5A (DV)  Ton  1233.522     983  2414.661  2198.795  2197.301  2170.99  2442.916  2148.882  1718.913  1753.955   1649.3    2061.215  NaN  4631.183  6567.086  6310.711     5464.47  NaN  NaN  NaN
1                          Coal/ Than 4A.1 (DV)  Ton       443  251.25   543.069    88.335    774.19  319.418    508.88   630.609   444.559      18.9   113.76     369.092  NaN  1237.319  1181.943  1584.048     501.752  NaN  NaN  NaN
2  Coal/ Than import coal (DV) (than nhập khẩu)  Ton         0   92.48   430.117   722.734         0   434.63    375.27     77.21         0    550.88  352.255     533.023  NaN   522.597  1157.364    452.48    1436.158  NaN  NaN  NaN
3   Than cám qua sàng / Than 5A under screen DV  Ton       114      88   206.339   209.205   204.699   201.01   188.848   204.034   133.775   153.045    156.7     175.785  NaN   408.339   614.914   526.657      485.53  NaN  NaN  NaN
4                            Coal/ Than 5A (YB)  Ton         0       0         0       NaN       NaN      NaN       NaN       NaN       NaN       NaN      NaN         NaN  NaN         0         0         0           0  NaN  NaN  NaN
5                          Coal/ Than 4A.1 (YB)  Ton         0       0         0       NaN       NaN      NaN       NaN       NaN       NaN       NaN      NaN   27.623114  NaN         0         0         0   27.623114  NaN  NaN  NaN
6  Coal/ Than import coal (YB) (than nhập khẩu)  Ton         0       0         0       NaN       NaN      NaN       NaN       NaN       NaN       NaN      NaN         NaN  NaN         0         0         0           0  NaN  NaN  NaN
7   Than cám qua sàng / Than 5A under screen YB  Ton         0       0         0       NaN       NaN      NaN       NaN       NaN       NaN       NaN      NaN         NaN  NaN         0         0         0           0  NaN  NaN  NaN
8                         Coal/ Than 5A (DV+YB)  Ton  1233.522     983  2414.661  2198.795  2197.301  2170.99  2442.916  2148.882  1718.913  1753.955   1649.3    2061.215    0  4631.183  6567.086  6310.711     5464.47  NaN  NaN  NaN
9                       Coal/ Than 4A.1 (DV+YB)  Ton       443  251.25   543.069    88.335    774.19  319.418    508.88   630.609   444.559      18.9   113.76  396.715115    0  1237.319  1181.943  1584.048  529.375114  NaN  NaN  NaN
Greenhouse Gas Emission
30 hàng x 22 cột
66                                                     Greenhouse Gas Emission        unit       Jan       Feb       Mar       Apr      May       Jun       Jul       Aug       Sep       Oct       Nov       Dec        YTD        Q1        Q2        Q3        Q4  NaN  NaN  NaN
0                                  Diesel oil (Station)/ Dầu cho máy phát điện       Litre      2000         0      5500      2000        0         0      2000         0      4000         0      5000     18000      38500      7500      2000      6000     23000  NaN  NaN  NaN
1                       Acetylene (Station)/ Khí axetilen cho máy Oxi Axetilen          kg       NaN       NaN       NaN       NaN      NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN          0         0         0         0         0  NaN  NaN  NaN
2                LPG for Welding (Station)/ Gas cho máy cắt Oxi Axetilen (hàn)          kg        72       108        12        12       24        12         0       NaN       NaN       NaN        36         0        276       192        48         0        36  NaN  NaN  NaN
3                                Calcium Carbonate ≥900OC (process)/ Bột CaCO3         ton   1185.21    903.63  2451.735  2133.495  2066.22  2160.795  2501.265   2094.69   1523.34  1624.155   1624.35   1872.75  22141.635  4540.575   6360.51  6119.295  5121.255  NaN  NaN  NaN
4                                        Anaerobic Wastewater: Average of flow      m3/day       NaN       NaN       NaN       NaN      NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN        NaN       NaN       NaN       NaN       NaN  NaN  NaN  NaN
5   Anaerobic Wastewater: COD (Enter anaerobic zone)/ \nNhu cầu Oxi để oxi hóa    mg COD/l       NaN       NaN       NaN       NaN      NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN        NaN       NaN       NaN       NaN       NaN  NaN  NaN  NaN
6                              Anaerobic Wastewater: COD (Exit anaerobic zone)    mg COD/l       NaN       NaN       NaN       NaN      NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN        NaN       NaN       NaN       NaN       NaN  NaN  NaN  NaN
7                                                Anaerobic Wastewater: Summary      kg CH4         0         0         0         0        0         0         0         0         0         0         0         0        NaN       NaN       NaN       NaN       NaN  NaN  NaN  NaN
8                                          Coal Gas CO2 Conversion factor (DV)  kgCO2/Mcal  0.620139  0.904083  0.611162  0.606448  0.63573  0.618829  0.618395  0.601653  0.580441  0.639098  0.579873  0.645281   0.623105  0.658306  0.620151  0.602282   0.62281  NaN  NaN  NaN
9                                           Coal Gas CO2 Conversion factor(YB)  kgCO2/Mcal         0         0         0         0        0         0         0         0         0         0         0         0          0         0         0         0         0  NaN  NaN  NaN
Conversion Factor
20 hàng x 22 cột
97            Conversion Factor Heat unit to GJ (Energy)      NaN            NaN Heat unit to kg CO2 eq      NaN            NaN 19.249179  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
0                    Coal/ Than                      NaN      NaN            NaN             kgCO2eq/GJ       96          Plant       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1              Lignite/Than non                   GJ/Ton      NaN          Plant            kgCO2eq/Ton      NaN          Plant       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2                   Natural Gas                 GJ/MMBTU    1.055  SCG SD Office          kgCO2eq/MMBTU  59.2399  SCG SD Office       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3          Co-generation (Heat)                 GJ/MMBTU    1.055  SCG SD Office          kgCO2eq/MMBTU      NaN          Plant       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4                 LPG (Station)                    GJ/kg   0.0493  SCG SD Office             kgCO2eq/kg   3.1133  SCG SD Office       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
5                  LPG (Mobile)                      NaN      NaN            NaN             kgCO2eq/kg   3.1899  SCG SD Office       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
6   Heavy fuel oil / Bunker oil                 GJ/Litre  0.03977  SCG SD Office          kgCO2eq/Litre   3.0833        SOD CBM       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
7           Diesel oil (Mobile)                 GJ/Litre  0.03642  SCG SD Office          kgCO2eq/Litre   2.7403  SCG SD Office       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
8          Diesel oil (Station)                      NaN      NaN            NaN          kgCO2eq/Litre   2.7076  SCG SD Office       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
9                      Gasoline                 GJ/Litre  0.03148  SCG SD Office          kgCO2eq/Litre   2.2376  SCG SD Office       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
Energy Cost
13 hàng x 22 cột
118                       Energy Cost            unit  Jan  Feb  Mar  Apr  May  Jun  Jul  Aug  Sep  Oct  Nov  Dec  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
0                                Coal  Local Currency  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1                             Lignite  Local Currency  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2                         Natural Gas  Local Currency  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3                Co-generation (Heat)  Local Currency  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4                                 LPG  Local Currency  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
5         Heavy fuel oil / Bunker oil  Local Currency  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
6                              Diesel         Ringgit  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
7                            Gasoline  Local Currency  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
8                               Steam  Local Currency  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
9    Solid Biomass (Renewable Energy)  Local Currency  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

In [ ]:
import re

for i, (start_idx, section) in enumerate(sorted_sections):
    end_idx = sorted_sections[i + 1][0] if i < len(sorted_sections) - 1 else len(energy_df)
    df_part = energy_df.iloc[start_idx:end_idx].copy()
    df_part_clean = pd.DataFrame(df_part.iloc[1:].values, columns=df_part.iloc[0])
    print(section)
    print(len(df_part_clean), "hàng x", len(df_part_clean.columns), "cột")
    print(df_part_clean.head(10).to_string())

    safe_section = re.sub(r'[^A-Za-z0-9_]+', '_', section)
    df_part_clean.to_csv(f"{safe_section}.csv", index=False)

Energy Consumption
65 hàng x 22 cột
0                            Energy Consumption unit       Jan     Feb       Mar       Apr       May      Jun       Jul       Aug       Sep       Oct      Nov         Dec  YTD        Q1        Q2        Q3          Q4  NaN  NaN  NaN
0                            Coal/ Than 5A (DV)  Ton  1233.522     983  2414.661  2198.795  2197.301  2170.99  2442.916  2148.882  1718.913  1753.955   1649.3    2061.215  NaN  4631.183  6567.086  6310.711     5464.47  NaN  NaN  NaN
1                          Coal/ Than 4A.1 (DV)  Ton       443  251.25   543.069    88.335    774.19  319.418    508.88   630.609   444.559      18.9   113.76     369.092  NaN  1237.319  1181.943  1584.048     501.752  NaN  NaN  NaN
2  Coal/ Than import coal (DV) (than nhập khẩu)  Ton         0   92.48   430.117   722.734         0   434.63    375.27     77.21         0    550.88  352.255     533.023  NaN   522.597  1157.364    452.48    1436.158  NaN  NaN  NaN
3   Than cám qua sàng / Than 5A under screen DV  Ton       114      88   206.339   209.205   204.699   201.01   188.848   204.034   133.775   153.045    156.7     175.785  NaN   408.339   614.914   526.657      485.53  NaN  NaN  NaN
4                            Coal/ Than 5A (YB)  Ton         0       0         0       NaN       NaN      NaN       NaN       NaN       NaN       NaN      NaN         NaN  NaN         0         0         0           0  NaN  NaN  NaN
5                          Coal/ Than 4A.1 (YB)  Ton         0       0         0       NaN       NaN      NaN       NaN       NaN       NaN       NaN      NaN   27.623114  NaN         0         0         0   27.623114  NaN  NaN  NaN
6  Coal/ Than import coal (YB) (than nhập khẩu)  Ton         0       0         0       NaN       NaN      NaN       NaN       NaN       NaN       NaN      NaN         NaN  NaN         0         0         0           0  NaN  NaN  NaN
7   Than cám qua sàng / Than 5A under screen YB  Ton         0       0         0       NaN       NaN      NaN       NaN       NaN       NaN       NaN      NaN         NaN  NaN         0         0         0           0  NaN  NaN  NaN
8                         Coal/ Than 5A (DV+YB)  Ton  1233.522     983  2414.661  2198.795  2197.301  2170.99  2442.916  2148.882  1718.913  1753.955   1649.3    2061.215    0  4631.183  6567.086  6310.711     5464.47  NaN  NaN  NaN
9                       Coal/ Than 4A.1 (DV+YB)  Ton       443  251.25   543.069    88.335    774.19  319.418    508.88   630.609   444.559      18.9   113.76  396.715115    0  1237.319  1181.943  1584.048  529.375114  NaN  NaN  NaN
Greenhouse Gas Emission
30 hàng x 22 cột
66                                                     Greenhouse Gas Emission        unit       Jan       Feb       Mar       Apr      May       Jun       Jul       Aug       Sep       Oct       Nov       Dec        YTD        Q1        Q2        Q3        Q4  NaN  NaN  NaN
0                                  Diesel oil (Station)/ Dầu cho máy phát điện       Litre      2000         0      5500      2000        0         0      2000         0      4000         0      5000     18000      38500      7500      2000      6000     23000  NaN  NaN  NaN
1                       Acetylene (Station)/ Khí axetilen cho máy Oxi Axetilen          kg       NaN       NaN       NaN       NaN      NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN          0         0         0         0         0  NaN  NaN  NaN
2                LPG for Welding (Station)/ Gas cho máy cắt Oxi Axetilen (hàn)          kg        72       108        12        12       24        12         0       NaN       NaN       NaN        36         0        276       192        48         0        36  NaN  NaN  NaN
3                                Calcium Carbonate ≥900OC (process)/ Bột CaCO3         ton   1185.21    903.63  2451.735  2133.495  2066.22  2160.795  2501.265   2094.69   1523.34  1624.155   1624.35   1872.75  22141.635  4540.575   6360.51  6119.295  5121.255  NaN  NaN  NaN
4                                        Anaerobic Wastewater: Average of flow      m3/day       NaN       NaN       NaN       NaN      NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN        NaN       NaN       NaN       NaN       NaN  NaN  NaN  NaN
5   Anaerobic Wastewater: COD (Enter anaerobic zone)/ \nNhu cầu Oxi để oxi hóa    mg COD/l       NaN       NaN       NaN       NaN      NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN        NaN       NaN       NaN       NaN       NaN  NaN  NaN  NaN
6                              Anaerobic Wastewater: COD (Exit anaerobic zone)    mg COD/l       NaN       NaN       NaN       NaN      NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN        NaN       NaN       NaN       NaN       NaN  NaN  NaN  NaN
7                                                Anaerobic Wastewater: Summary      kg CH4         0         0         0         0        0         0         0         0         0         0         0         0        NaN       NaN       NaN       NaN       NaN  NaN  NaN  NaN
8                                          Coal Gas CO2 Conversion factor (DV)  kgCO2/Mcal  0.620139  0.904083  0.611162  0.606448  0.63573  0.618829  0.618395  0.601653  0.580441  0.639098  0.579873  0.645281   0.623105  0.658306  0.620151  0.602282   0.62281  NaN  NaN  NaN
9                                           Coal Gas CO2 Conversion factor(YB)  kgCO2/Mcal         0         0         0         0        0         0         0         0         0         0         0         0          0         0         0         0         0  NaN  NaN  NaN
Conversion Factor
20 hàng x 22 cột
97            Conversion Factor Heat unit to GJ (Energy)      NaN            NaN Heat unit to kg CO2 eq      NaN            NaN 19.249179  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
0                    Coal/ Than                      NaN      NaN            NaN             kgCO2eq/GJ       96          Plant       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1              Lignite/Than non                   GJ/Ton      NaN          Plant            kgCO2eq/Ton      NaN          Plant       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2                   Natural Gas                 GJ/MMBTU    1.055  SCG SD Office          kgCO2eq/MMBTU  59.2399  SCG SD Office       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3          Co-generation (Heat)                 GJ/MMBTU    1.055  SCG SD Office          kgCO2eq/MMBTU      NaN          Plant       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4                 LPG (Station)                    GJ/kg   0.0493  SCG SD Office             kgCO2eq/kg   3.1133  SCG SD Office       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
5                  LPG (Mobile)                      NaN      NaN            NaN             kgCO2eq/kg   3.1899  SCG SD Office       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
6   Heavy fuel oil / Bunker oil                 GJ/Litre  0.03977  SCG SD Office          kgCO2eq/Litre   3.0833        SOD CBM       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
7           Diesel oil (Mobile)                 GJ/Litre  0.03642  SCG SD Office          kgCO2eq/Litre   2.7403  SCG SD Office       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
8          Diesel oil (Station)                      NaN      NaN            NaN          kgCO2eq/Litre   2.7076  SCG SD Office       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
9                      Gasoline                 GJ/Litre  0.03148  SCG SD Office          kgCO2eq/Litre   2.2376  SCG SD Office       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
Energy Cost
13 hàng x 22 cột
118                       Energy Cost            unit  Jan  Feb  Mar  Apr  May  Jun  Jul  Aug  Sep  Oct  Nov  Dec  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
0                                Coal  Local Currency  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1                             Lignite  Local Currency  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2                         Natural Gas  Local Currency  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3                Co-generation (Heat)  Local Currency  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4                                 LPG  Local Currency  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
5         Heavy fuel oil / Bunker oil  Local Currency  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
6                              Diesel         Ringgit  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
7                            Gasoline  Local Currency  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
8                               Steam  Local Currency  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
9    Solid Biomass (Renewable Energy)  Local Currency  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

Production, Raw Mat

In [ ]:
# sheet 'Energy, GHG'
df_production = pd.read_excel(excel_file, sheet_name='Production, Raw Mat')
print(df_production.head(10))

                                      Unnamed: 0 Unnamed: 1 Unnamed: 2  \
0               Production (DV Tile + YB Powder)       unit        Jan
1             Production (DV Tile) (Sản phẩm ĐV)        ton   9609.931
2  Production (YB Powder) (bột bán cho Yên Bình)        ton          0
3                     Total Production (DV + YB)        ton   9609.931
4                                            NaN        NaN        NaN
5                                   Raw Material       unit        Jan
6                     Limestone/ Đá vôi (canxit)        ton    1185.21
7                                  Clay/ Đất sét        ton    6280.95
8                                      Sand/ Cát        ton        NaN
9                              Gypsum/ Thạch cao        ton        NaN

    Unnamed: 3   Unnamed: 4   Unnamed: 5   Unnamed: 6   Unnamed: 7  \
0          Feb          Mar          Apr          May          Jun
1  6310.080933  17732.97347  15795.45537  16091.79977  16408.01583
2            0            0            0            0          NaN
3  6310.080933  17732.97347  15795.45537  16091.79977  16408.01583
4          NaN          NaN          NaN          NaN          NaN
5          Feb          Mar          Apr          May          Jun
6       903.63     2451.735     2133.495      2066.22     2160.795
7       4812.6     13112.58     11433.24    11029.452     11323.65
8          NaN          NaN          NaN          NaN          NaN
9          NaN          NaN          NaN          NaN          NaN

   Unnamed: 8   Unnamed: 9  Unnamed: 10  Unnamed: 11  Unnamed: 12  \
0         Jul          Aug          Sep          Oct          Nov
1  18454.3238  16179.63025  12136.76037  12464.84122  12324.14555
2         NaN          NaN          NaN          NaN          NaN
3  18454.3238  16179.63025  12136.76037  12464.84122  12324.14555
4         NaN          NaN          NaN          NaN          NaN
5         Jul          Aug          Sep          Oct          Nov
6    2501.265      2094.69      1523.34     1624.155      1624.35
7   13526.175    12506.465      8783.97      9729.72     9687.405
8         NaN          NaN          NaN          NaN          NaN
9         NaN          NaN          NaN          NaN          NaN

   Unnamed: 13  Unnamed: 14 Unnamed: 15  Unnamed: 16  Unnamed: 17  Unnamed: 18
0          Dec          YTD          Q1           Q2           Q3           Q4
1  15580.26882  169088.2264  33652.9854  48295.27097  46770.71442  40369.25559
2     423.6674     423.6674           0            0            0     423.6674
3  16003.93622  169511.8938  33652.9854  48295.27097  46770.71442  40792.92299
4          NaN          NaN         NaN          NaN          NaN          NaN
5          Dec          YTD          Q1           Q2           Q3           Q4
6      1872.75    22141.635    4540.575      6360.51     6119.295     5121.255
7    11518.615   123744.822    24206.13    33786.342     34816.61     30935.74
8          NaN            0           0            0            0            0
9          NaN            0           0            0            0            0

In [ ]:
pro_df = df_production.reset_index(drop=True)
section_names = ['Production (DV Tile + YB Powder)', 'Raw Material']
section_markers = find_sections(pro_df, section_names)
sorted_sections = sorted([(section_markers[s], s) for s in section_names if s in section_markers])

for i, (start_idx, section) in enumerate(sorted_sections):
    end_idx = sorted_sections[i + 1][0] if i < len(sorted_sections) - 1 else len(pro_df)
    df_part = pro_df.iloc[start_idx:end_idx].copy()
    df_part_clean = pd.DataFrame(df_part.iloc[1:].values, columns=df_part.iloc[0])
    print(section)
    print(len(df_part_clean), "hàng x", len(df_part_clean.columns), "cột")
    print(df_part_clean.head(10).to_string())

Production (DV Tile + YB Powder)
4 hàng x 19 cột
0               Production (DV Tile + YB Powder) unit       Jan          Feb          Mar          Apr          May          Jun         Jul          Aug          Sep          Oct          Nov          Dec          YTD          Q1           Q2           Q3           Q4
0             Production (DV Tile) (Sản phẩm ĐV)  ton  9609.931  6310.080933  17732.97347  15795.45537  16091.79977  16408.01583  18454.3238  16179.63025  12136.76037  12464.84122  12324.14555  15580.26882  169088.2264  33652.9854  48295.27097  46770.71442  40369.25559
1  Production (YB Powder) (bột bán cho Yên Bình)  ton         0            0            0            0            0          NaN         NaN          NaN          NaN          NaN          NaN     423.6674     423.6674           0            0            0     423.6674
2                     Total Production (DV + YB)  ton  9609.931  6310.080933  17732.97347  15795.45537  16091.79977  16408.01583  18454.3238  16179.63025  12136.76037  12464.84122  12324.14555  16003.93622  169511.8938  33652.9854  48295.27097  46770.71442  40792.92299
3                                            NaN  NaN       NaN          NaN          NaN          NaN          NaN          NaN         NaN          NaN          NaN          NaN          NaN          NaN          NaN         NaN          NaN          NaN          NaN
Raw Material
14 hàng x 19 cột
5                       Raw Material unit      Jan      Feb       Mar       Apr        May       Jun        Jul        Aug      Sep       Oct       Nov        Dec         YTD        Q1         Q2        Q3        Q4
0         Limestone/ Đá vôi (canxit)  ton  1185.21   903.63  2451.735  2133.495    2066.22  2160.795   2501.265    2094.69  1523.34  1624.155   1624.35    1872.75   22141.635  4540.575    6360.51  6119.295  5121.255
1                      Clay/ Đất sét  ton  6280.95   4812.6  13112.58  11433.24  11029.452  11323.65  13526.175  12506.465  8783.97   9729.72  9687.405  11518.615  123744.822  24206.13  33786.342  34816.61  30935.74
2                          Sand/ Cát  ton      NaN      NaN       NaN       NaN        NaN       NaN        NaN        NaN      NaN       NaN       NaN        NaN           0         0          0         0         0
3                  Gypsum/ Thạch cao  ton      NaN      NaN       NaN       NaN        NaN       NaN        NaN        NaN      NaN       NaN       NaN        NaN           0         0          0         0         0
4                   Laterite/ Đá ong  ton      NaN      NaN       NaN       NaN        NaN       NaN        NaN        NaN      NaN       NaN       NaN        NaN           0         0          0         0         0
5                    Cement/ Xi măng  ton      NaN      NaN       NaN       NaN        NaN       NaN        NaN        NaN      NaN       NaN       NaN        NaN           0         0          0         0         0
6                           Feldspar  ton   696.15    772.2    1762.8   1414.14   1600.308   1814.67    2458.17      963.3   958.62     877.5     627.9     1141.7   15087.458   3231.15   4829.118   4380.09    2647.1
7             Aggregate/ Chất kết tụ  ton      NaN      NaN       NaN       NaN        NaN       NaN        NaN        NaN      NaN       NaN       NaN        NaN           0         0          0         0         0
8                      Pottery Stone  ton      NaN      NaN       NaN       NaN        NaN       NaN        NaN        NaN      NaN       NaN       NaN        NaN           0         0          0         0         0
9  Glazing (Men ướt nhập VP quy khô)  ton   611.66  593.122  1366.899  1232.648   1224.313  1274.894   1532.653   1223.418  908.336   1025.46   906.515   1268.747   13168.665  2571.681   3731.855  3664.407  3200.722

Water

In [ ]:
water_df = pd.read_excel(excel_file, sheet_name='Water')
print(water_df.head(10))

                                     Unnamed: 0 Unnamed: 1 Unnamed: 2  \
0                              Water Withdrawal       unit        Jan
1          Surface water (Lake) (DV) (Nước mặt)         m3       4987
2          Surface water (Lake) (YB) (Nước Mặt)         m3          0
3  Surface water (Lake) (DV+YB) (tổng nước mặt)         m3       4987
4                     Ground water (wells) (DV)         m3          0
5                     Tap wate (DV) (Nước sạch)         m3        658
6                   Total Water Withdrawal (DV)         m3       5645
7                   Total Water Withdrawal (YB)         m3          0
8                Total Water Withdrawal (DV+YB)         m3       5645
9                Specific Water Withdrawal (DV)     m3/ton   0.587413

  Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6 Unnamed: 7 Unnamed: 8  \
0        Feb        Mar        Apr        May        Jun        Jul
1       3058       6675       6392       6393       6254       6934
2          0          0          0          0          0          0
3       3058       6675       6392       6393       6254       6934
4          0          0          0          0          0          0
5       1198       1079       1292        631       1524       2083
6       4256       7754       7684       7024       7778       9017
7          0          0          0          0          0          0
8       4256       7754       7684       7024       7778       9017
9   0.674476   0.437265   0.486469   0.436496   0.474037   0.488612

  Unnamed: 9 Unnamed: 10 Unnamed: 11 Unnamed: 12 Unnamed: 13 Unnamed: 14  \
0        Aug         Sep         Oct         Nov         Dec         YTD
1       6241        5438        6081        6741        7894       73088
2          0           0           0           0           0           0
3       6241        5438        6081        6741        7894       73088
4          0         NaN         NaN         NaN         NaN           0
5       1586        1369        1289        1726        1064       15499
6       7827        6807        7370        8467        8958       88587
7          0           0           0           0           0           0
8       7827        6807        7370        8467        8958       88587
9   0.483756    0.560858    0.591263    0.687025    0.574958     #ERROR!

  Unnamed: 15 Unnamed: 16 Unnamed: 17 Unnamed: 18
0          Q1          Q2          Q3          Q4
1       14720       19039       18613       20716
2           0           0           0           0
3       14720       19039       18613       20716
4           0           0           0           0
5        2935        3447        5038        4079
6       17655       22486       23651       24795
7           0           0           0           0
8       17655       22486       23651       24795
9     #ERROR!     #ERROR!     #ERROR!     #ERROR!

In [ ]:
water_df = water_df.reset_index(drop=True)
section_names = ['Water Withdrawal', 'Water Recycle']
section_markers = find_sections(water_df, section_names)
sorted_sections = sorted([(section_markers[s], s) for s in section_names if s in section_markers])
for i, (start_idx, section) in enumerate(sorted_sections):
    end_idx = sorted_sections[i + 1][0] if i < len(sorted_sections) - 1 else len(water_df)
    df_part = water_df.iloc[start_idx:end_idx].copy()
    df_part_clean = pd.DataFrame(df_part.iloc[1:].values, columns=df_part.iloc[0])
    print(section)
    print(len(df_part_clean), "hàng x", len(df_part_clean.columns), "cột")
    print(df_part_clean.head(10).to_string())

Water Withdrawal
12 hàng x 19 cột
0                              Water Withdrawal    unit       Jan       Feb       Mar       Apr       May       Jun       Jul       Aug       Sep       Oct       Nov       Dec      YTD       Q1       Q2       Q3       Q4
0          Surface water (Lake) (DV) (Nước mặt)      m3      4987      3058      6675      6392      6393      6254      6934      6241      5438      6081      6741      7894    73088    14720    19039    18613    20716
1          Surface water (Lake) (YB) (Nước Mặt)      m3         0         0         0         0         0         0         0         0         0         0         0         0        0        0        0        0        0
2  Surface water (Lake) (DV+YB) (tổng nước mặt)      m3      4987      3058      6675      6392      6393      6254      6934      6241      5438      6081      6741      7894    73088    14720    19039    18613    20716
3                     Ground water (wells) (DV)      m3         0         0         0         0         0         0         0         0       NaN       NaN       NaN       NaN        0        0        0        0        0
4                     Tap wate (DV) (Nước sạch)      m3       658      1198      1079      1292       631      1524      2083      1586      1369      1289      1726      1064    15499     2935     3447     5038     4079
5                   Total Water Withdrawal (DV)      m3      5645      4256      7754      7684      7024      7778      9017      7827      6807      7370      8467      8958    88587    17655    22486    23651    24795
6                   Total Water Withdrawal (YB)      m3         0         0         0         0         0         0         0         0         0         0         0         0        0        0        0        0        0
7                Total Water Withdrawal (DV+YB)      m3      5645      4256      7754      7684      7024      7778      9017      7827      6807      7370      8467      8958    88587    17655    22486    23651    24795
8                Specific Water Withdrawal (DV)  m3/ton  0.587413  0.674476  0.437265  0.486469  0.436496  0.474037  0.488612  0.483756  0.560858  0.591263  0.687025  0.574958  #ERROR!  #ERROR!  #ERROR!  #ERROR!  #ERROR!
9                Specific Water Withdrawal (YB)  m3/ton   #DIV/0!   #DIV/0!   #DIV/0!   #DIV/0!   #DIV/0!   #DIV/0!   #DIV/0!   #DIV/0!   #DIV/0!   #DIV/0!   #DIV/0!         0        0  #DIV/0!  #DIV/0!  #DIV/0!        0
Water Recycle
7 hàng x 19 cột
13                    Water Recycle unit                              Jan    Feb   Mar   Apr    May    Jun    Jul    Aug    Sep    Oct    Nov    Dec   YTD     Q1     Q2     Q3     Q4
0   Water Recycle/ Nước tái sử dụng   m3                             3047   2139  5669  5231   4453   4245   6172   5372   4704   4552   5187   5392   NaN  10855  13929  16248  15131
1                               NaN  NaN                              NaN    NaN   NaN   NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   NaN    NaN    NaN    NaN    NaN
2                   Ko có nước ngầm  NaN                              NaN    NaN   NaN   NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   NaN    NaN    NaN    NaN    NaN
3                               NaN  NaN                              NaN    NaN   NaN   NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   NaN    NaN    NaN    NaN    NaN
4                   Ko có nước ngầm  NaN                              NaN    Jan   Feb   Mar    Apr    May    Jun    Jul    Aug    Sep    Oct    Nov   Dec    NaN    NaN    NaN    NaN
5                               NaN  NaN           Total Water Withdrawal  12839  6903  9043  11134  14106  13676  13709  12091  12437  10166  12485     0    NaN    NaN    NaN    NaN
6                               NaN  NaN  Water Recycle/ Nước tái sử dụng   4254  1350  4198   4986   5449   4655   4177   5816   5681   5544   4951   NaN    NaN    NaN    NaN    NaN

#Waste

In [ ]:
waste_df = pd.read_excel(excel_file, sheet_name='Waste')
print(waste_df.head(10))

                                          Unnamed: 0               Unnamed: 1  \
0          Hazardous Waste (ton)/ CHẤT THẢI NGUY HẠI                      Jan
1                                                NaN  Incoming Stock/ Tồn đầu
2                                                NaN                      NaN
3  Contaminated Cloth/ Bao gồm giẻ lau, gang tay ...                   0.3472
4  Used oil/ Tất cả các loại dầu đã qua sử dụng thải                   5.8526
5  Package contaminated / Vỏ thùng sơn, vỏ thùng ...                    2.413
6  Electronic equipment / Các thiết bị điện thải ...                   0.1484
7  Insulation/ Vật liệu cách nhiệt (amiăng thải, ...                   1.6998
8                                  Đất dính hóa chất                   0.2316
9                     Cặn rắn từ quá trình sử lý men                     0.04

                             Unnamed: 2                  Unnamed: 3  \
0                                   NaN                         NaN
1  Waste generated/ Chất thải phát sinh            Waste Management
2                                   NaN  Reuse/Recycle/ Tái sử dụng
3                                  0.03                         NaN
4                                     0                         NaN
5                                0.1281                         NaN
6                                 0.013                         NaN
7                                 0.029                         NaN
8                                     0                         NaN
9                                     0                         NaN

                    Unnamed: 4                    Unnamed: 5  \
0                          NaN                           NaN
1                          NaN                           NaN
2  Incineration/ Chất thải đốt  Landfill/ CHất thải chôn lấp
3                          NaN                           NaN
4                          NaN                           NaN
5                          NaN                           NaN
6                          NaN                           NaN
7                          NaN                           NaN
8                          NaN                           NaN
9                          NaN                           NaN

                Unnamed: 6                            Unnamed: 7  \
0                      Feb                                   NaN
1  Incoming Stock/ Tồn đầu  Waste generated/ Chất thải phát sinh
2                      NaN                                   NaN
3                   0.3772                                0.4042
4                   5.8526                                6.0424
5                   2.5411                                0.1866
6                   0.1614                                 0.022
7                   1.7288                                0.3042
8                   0.2316                                     0
9                     0.04                                     0

                   Unnamed: 8                   Unnamed: 9  ...  \
0                         NaN                          NaN  ...
1            Waste Management                          NaN  ...
2  Reuse/Recycle/ Tái sử dụng  Incineration/ Chất thải đốt  ...
3                         NaN                          NaN  ...
4                         NaN                       11.095  ...
5                       0.805                          NaN  ...
6                         NaN                          NaN  ...
7                         NaN                          NaN  ...
8                         NaN                          NaN  ...
9                         NaN                          NaN  ...

                            Unnamed: 57                 Unnamed: 58  \
0                                   NaN                         NaN
1  Waste generated/ Chất thải phát sinh            Waste Management
2                                   NaN  Reuse/Recycle/ Tái sử dụng
3                                 0.182                         NaN
4                                   1.7                         NaN
5                                 0.185                         NaN
6                                 0.005                         NaN
7                                  0.03                         NaN
8                                     0                         NaN
9                                     0                         NaN

                   Unnamed: 59                   Unnamed: 60  \
0                          NaN                           NaN
1                          NaN                           NaN
2  Incineration/ Chất thải đốt  Landfill/ CHất thải chôn lấp
3                          NaN                           NaN
4                          NaN                           NaN
5                          NaN                           NaN
6                          NaN                           NaN
7                          NaN                           NaN
8                          NaN                           NaN
9                          NaN                           NaN

                  Unnamed: 61               Unnamed: 62  \
0                         NaN                       NaN
1  Outgoing Stock\n(Estimate)  Outgoing Stock\n(Actual)
2                         NaN                       NaN
3                      1.8102                       NaN
4                       3.038                       NaN
5                       1.975                       NaN
6                      0.1883                       NaN
7                      1.2523                       NaN
8                      0.2316                       NaN
9                        0.04                       NaN

                 Unnamed: 63      Unnamed: 64 Unnamed: 65 Unnamed: 66
0                        NaN  Total (Jan-Dec)         NaN         NaN
1  Waste generated\n(Actual)  Waste generated    Landfill         NaN
2                        NaN              NaN         NaN         NaN
3                    -1.6282              NaN         NaN      2.2630
4                     -1.338              NaN         NaN      0.4528
5                      -1.79              NaN         NaN         NaN
6                    -0.1833              NaN         NaN         NaN
7                    -1.2223              NaN         NaN         NaN
8                    -0.2316              NaN         NaN         NaN
9                      -0.04              NaN         NaN         NaN

[10 rows x 67 columns]

In [ ]:
df_waste = waste_df.reset_index(drop=True)
df_waste.info()
df_waste.head(10)
section_names = ['Hazardous Waste (ton)/ CHẤT THẢI NGUY HẠI', 'Non Hazardous Waste (ton)/ CHẤT THẢI THÔNG THƯỜNG']

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 67 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   24 non-null     object
 1   Unnamed: 1   24 non-null     object
 2   Unnamed: 2   24 non-null     object
 3   Unnamed: 3   10 non-null     object
 4   Unnamed: 4   4 non-null      object
 5   Unnamed: 5   6 non-null      object
 6   Unnamed: 6   24 non-null     object
 7   Unnamed: 7   24 non-null     object
 8   Unnamed: 8   8 non-null      object
 9   Unnamed: 9   6 non-null      object
 10  Unnamed: 10  6 non-null      object
 11  Unnamed: 11  24 non-null     object
 12  Unnamed: 12  23 non-null     object
 13  Unnamed: 13  12 non-null     object
 14  Unnamed: 14  4 non-null      object
 15  Unnamed: 15  6 non-null      object
 16  Unnamed: 16  24 non-null     object
 17  Unnamed: 17  23 non-null     object
 18  Unnamed: 18  6 non-null      object
 19  Unnamed: 19  4 non-null      object
 20  Unnamed: 20  6 non-null      object
 21  Unnamed: 21  24 non-null     object
 22  Unnamed: 22  24 non-null     object
 23  Unnamed: 23  9 non-null      object
 24  Unnamed: 24  4 non-null      object
 25  Unnamed: 25  6 non-null      object
 26  Unnamed: 26  24 non-null     object
 27  Unnamed: 27  24 non-null     object
 28  Unnamed: 28  9 non-null      object
 29  Unnamed: 29  5 non-null      object
 30  Unnamed: 30  6 non-null      object
 31  Unnamed: 31  24 non-null     object
 32  Unnamed: 32  23 non-null     object
 33  Unnamed: 33  8 non-null      object
 34  Unnamed: 34  4 non-null      object
 35  Unnamed: 35  6 non-null      object
 36  Unnamed: 36  24 non-null     object
 37  Unnamed: 37  23 non-null     object
 38  Unnamed: 38  8 non-null      object
 39  Unnamed: 39  6 non-null      object
 40  Unnamed: 40  6 non-null      object
 41  Unnamed: 41  24 non-null     object
 42  Unnamed: 42  23 non-null     object
 43  Unnamed: 43  8 non-null      object
 44  Unnamed: 44  4 non-null      object
 45  Unnamed: 45  6 non-null      object
 46  Unnamed: 46  24 non-null     object
 47  Unnamed: 47  23 non-null     object
 48  Unnamed: 48  6 non-null      object
 49  Unnamed: 49  5 non-null      object
 50  Unnamed: 50  6 non-null      object
 51  Unnamed: 51  24 non-null     object
 52  Unnamed: 52  23 non-null     object
 53  Unnamed: 53  9 non-null      object
 54  Unnamed: 54  4 non-null      object
 55  Unnamed: 55  6 non-null      object
 56  Unnamed: 56  24 non-null     object
 57  Unnamed: 57  22 non-null     object
 58  Unnamed: 58  8 non-null      object
 59  Unnamed: 59  4 non-null      object
 60  Unnamed: 60  6 non-null      object
 61  Unnamed: 61  22 non-null     object
 62  Unnamed: 62  4 non-null      object
 63  Unnamed: 63  24 non-null     object
 64  Unnamed: 64  9 non-null      object
 65  Unnamed: 65  7 non-null      object
 66  Unnamed: 66  2 non-null      float64
dtypes: float64(1), object(66)
memory usage: 15.8+ KB

In [ ]:
section_names = [
    'Hazardous Waste (ton)/ CHẤT THẢI NGUY HẠI',
    'Non Hazardous Waste (ton)/ CHẤT THẢI THÔNG THƯỜNG'
]
section_markers = find_sections(waste_df, section_names)
sorted_sections = sorted([(section_markers[s], s) for s in section_names if s in section_markers])

all_flat = []

for i, (start_idx, section) in enumerate(sorted_sections):
    end_idx = sorted_sections[i + 1][0] if i < len(sorted_sections) - 1 else len(waste_df)
    df_part = waste_df.iloc[start_idx:end_idx].copy()
    df_part_clean = pd.DataFrame(df_part.iloc[1:].values, columns=df_part.iloc[0])
    print(section)
    print(len(df_part_clean), "hàng x", len(df_part_clean.columns), "cột")
    print(df_part_clean.head(3).to_string())

    data = df_part_clean.iloc[3:].reset_index(drop=True)
    data.columns = [f"col_{i}" for i in range(data.shape[1])]

    for idx, row in data.iterrows():
        waste_category_en = row['col_0']
        for m, month in enumerate(['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']):
            base = 1 + m * 5
            record = {
                'section': section,
                'waste_category_en': waste_category_en,
                'report_month': month,
                'incoming_stock': row.get(f'col_{base}'),
                'waste_generated': row.get(f'col_{base+1}'),
                'reuse_recycle': row.get(f'col_{base+2}'),
                'incineration': row.get(f'col_{base+3}'),
                'landfill': row.get(f'col_{base+4}'),
            }
            all_flat.append(record)

df_flat = pd.DataFrame(all_flat)
print(df_flat.head(10))

Hazardous Waste (ton)/ CHẤT THẢI NGUY HẠI
14 hàng x 67 cột
0                              Hazardous Waste (ton)/ CHẤT THẢI NGUY HẠI                      Jan                                   NaN                         NaN                          NaN                           NaN                      Feb                                   NaN                         NaN                          NaN                           NaN                      Mar                                   NaN                         NaN                          NaN                           NaN                      Apr                                   NaN                         NaN                          NaN                           NaN                      May                                   NaN                         NaN                          NaN                           NaN                      Jun                                   NaN                         NaN                          NaN                           NaN                      Jul                                   NaN                         NaN                          NaN                           NaN                      Aug                                   NaN                         NaN                          NaN                           NaN                      Sep                                   NaN                         NaN                          NaN                           NaN                      Oct                                   NaN                         NaN                          NaN                           NaN                      Nov                                   NaN                         NaN                          NaN                           NaN                      Dec                                   NaN                         NaN                          NaN                           NaN                         NaN                       NaN                        NaN  Total (Jan-Dec)       NaN    NaN
0                                                                    NaN  Incoming Stock/ Tồn đầu  Waste generated/ Chất thải phát sinh            Waste Management                          NaN                           NaN  Incoming Stock/ Tồn đầu  Waste generated/ Chất thải phát sinh            Waste Management                          NaN                           NaN  Incoming Stock/ Tồn đầu  Waste generated/ Chất thải phát sinh            Waste Management                          NaN                           NaN  Incoming Stock/ Tồn đầu  Waste generated/ Chất thải phát sinh            Waste Management                          NaN                           NaN  Incoming Stock/ Tồn đầu  Waste generated/ Chất thải phát sinh            Waste Management                          NaN                           NaN  Incoming Stock/ Tồn đầu  Waste generated/ Chất thải phát sinh            Waste Management                          NaN                           NaN  Incoming Stock/ Tồn đầu  Waste generated/ Chất thải phát sinh            Waste Management                          NaN                           NaN  Incoming Stock/ Tồn đầu  Waste generated/ Chất thải phát sinh            Waste Management                          NaN                           NaN  Incoming Stock/ Tồn đầu  Waste generated/ Chất thải phát sinh            Waste Management                          NaN                           NaN  Incoming Stock/ Tồn đầu  Waste generated/ Chất thải phát sinh            Waste Management                          NaN                           NaN  Incoming Stock/ Tồn đầu  Waste generated/ Chất thải phát sinh            Waste Management                          NaN                           NaN  Incoming Stock/ Tồn đầu  Waste generated/ Chất thải phát sinh            Waste Management                          NaN                           NaN  Outgoing Stock\n(Estimate)  Outgoing Stock\n(Actual)  Waste generated\n(Actual)  Waste generated  Landfill    NaN
1                                                                    NaN                      NaN                                   NaN  Reuse/Recycle/ Tái sử dụng  Incineration/ Chất thải đốt  Landfill/ CHất thải chôn lấp                      NaN                                   NaN  Reuse/Recycle/ Tái sử dụng  Incineration/ Chất thải đốt  Landfill/ CHất thải chôn lấp                      NaN                                   NaN  Reuse/Recycle/ Tái sử dụng  Incineration/ Chất thải đốt  Landfill/ CHất thải chôn lấp                      NaN                                   NaN  Reuse/Recycle/ Tái sử dụng  Incineration/ Chất thải đốt  Landfill/ CHất thải chôn lấp                      NaN                                   NaN  Reuse/Recycle/ Tái sử dụng  Incineration/ Chất thải đốt  Landfill/ CHất thải chôn lấp                      NaN                                   NaN  Reuse/Recycle/ Tái sử dụng  Incineration/ Chất thải đốt  Landfill/ CHất thải chôn lấp                      NaN                                   NaN  Reuse/Recycle/ Tái sử dụng  Incineration/ Chất thải đốt  Landfill/ CHất thải chôn lấp                      NaN                                   NaN  Reuse/Recycle/ Tái sử dụng  Incineration/ Chất thải đốt  Landfill/ CHất thải chôn lấp                      NaN                                   NaN  Reuse/Recycle/ Tái sử dụng  Incineration/ Chất thải đốt  Landfill/ CHất thải chôn lấp                      NaN                                   NaN  Reuse/Recycle/ Tái sử dụng  Incineration/ Chất thải đốt  Landfill/ CHất thải chôn lấp                      NaN                                   NaN  Reuse/Recycle/ Tái sử dụng  Incineration/ Chất thải đốt  Landfill/ CHất thải chôn lấp                      NaN                                   NaN  Reuse/Recycle/ Tái sử dụng  Incineration/ Chất thải đốt  Landfill/ CHất thải chôn lấp                         NaN                       NaN                        NaN              NaN       NaN    NaN
2  Contaminated Cloth/ Bao gồm giẻ lau, gang tay dính hóa chất, dính dầu                   0.3472                                  0.03                         NaN                          NaN                           NaN                   0.3772                                0.4042                         NaN                          NaN                           NaN                   0.7814                                0.3202                         NaN                          NaN                           NaN                   1.1016                                0.2031                         NaN                          NaN                           NaN                   1.3047                                 0.114                         NaN                          NaN                           NaN                   1.4187                                 0.215                         NaN                          0.8                           NaN                   0.8337                                 0.149                         NaN                          NaN                           NaN                   0.9827                                 0.198                         NaN                          NaN                           NaN                   1.1807                                 0.136                         NaN                          NaN                           NaN                   1.3167                                0.1215                         NaN                          NaN                           NaN                   1.4382                                  0.19                         NaN                          NaN                           NaN                   1.6282                                 0.182                         NaN                          NaN                           NaN                      1.8102                       NaN                    -1.6282              NaN       NaN  2.263
Non Hazardous Waste (ton)/ CHẤT THẢI THÔNG THƯỜNG
14 hàng x 67 cột
15     Non Hazardous Waste (ton)/ CHẤT THẢI THÔNG THƯỜNG                      Jan                                   NaN                         NaN                          NaN                           NaN                      Feb                                   NaN                         NaN                          NaN                           NaN                      Mar                                   NaN                         NaN                          NaN                           NaN                      Apr                                   NaN                         NaN                          NaN                           NaN                      May                                   NaN                         NaN                          NaN                           NaN                      Jun                                   NaN                         NaN                          NaN                           NaN                      Jul                                   NaN                         NaN                          NaN                           NaN                      Aug                                   NaN                         NaN                          NaN                           NaN                      Sep                                   NaN                         NaN                          NaN                           NaN                      Oct                                   NaN                         NaN                          NaN                           NaN                      Nov                                   NaN                         NaN                          NaN                           NaN                      Dec                                   NaN                         NaN                          NaN                           NaN                         NaN                       NaN                        NaN  Total (Jan-Dec)       NaN  NaN
0                                                    NaN  Incoming Stock/ Tồn đầu  Waste generated/ Chất thải phát sinh            Waste Management                          NaN                           NaN  Incoming Stock/ Tồn đầu  Waste generated/ Chất thải phát sinh            Waste Management                          NaN                           NaN  Incoming Stock/ Tồn đầu  Waste generated/ Chất thải phát sinh            Waste Management                          NaN                           NaN  Incoming Stock/ Tồn đầu  Waste generated/ Chất thải phát sinh            Waste Management                          NaN                           NaN  Incoming Stock/ Tồn đầu  Waste generated/ Chất thải phát sinh            Waste Management                          NaN                           NaN  Incoming Stock/ Tồn đầu  Waste generated/ Chất thải phát sinh            Waste Management                          NaN                           NaN  Incoming Stock/ Tồn đầu  Waste generated/ Chất thải phát sinh            Waste Management                          NaN                           NaN  Incoming Stock/ Tồn đầu  Waste generated/ Chất thải phát sinh            Waste Management                          NaN                           NaN  Incoming Stock/ Tồn đầu  Waste generated/ Chất thải phát sinh            Waste Management                          NaN                           NaN  Incoming Stock/ Tồn đầu  Waste generated/ Chất thải phát sinh            Waste Management                          NaN                           NaN  Incoming Stock/ Tồn đầu  Waste generated/ Chất thải phát sinh            Waste Management                          NaN                           NaN  Incoming Stock/ Tồn đầu  Waste generated/ Chất thải phát sinh            Waste Management                          NaN                           NaN  Outgoing Stock\n(Estimate)  Outgoing Stock\n(Actual)  Waste generated\n(Actual)  Waste generated  Landfill  NaN
1                                                    NaN                      NaN                                   NaN  Reuse/Recycle/ Tái sử dụng  Incineration/ Chất thải đốt  Landfill/ CHất thải chôn lấp                      NaN                                   NaN  Reuse/Recycle/ Tái sử dụng  Incineration/ Chất thải đốt  Landfill/ CHất thải chôn lấp                      NaN                                   NaN  Reuse/Recycle/ Tái sử dụng  Incineration/ Chất thải đốt  Landfill/ CHất thải chôn lấp                      NaN                                   NaN  Reuse/Recycle/ Tái sử dụng  Incineration/ Chất thải đốt  Landfill/ CHất thải chôn lấp                      NaN                                   NaN  Reuse/Recycle/ Tái sử dụng  Incineration/ Chất thải đốt  Landfill/ CHất thải chôn lấp                      NaN                                   NaN  Reuse/Recycle/ Tái sử dụng  Incineration/ Chất thải đốt  Landfill/ CHất thải chôn lấp                      NaN                                   NaN  Reuse/Recycle/ Tái sử dụng  Incineration/ Chất thải đốt  Landfill/ CHất thải chôn lấp                      NaN                                   NaN  Reuse/Recycle/ Tái sử dụng  Incineration/ Chất thải đốt  Landfill/ CHất thải chôn lấp                      NaN                                   NaN  Reuse/Recycle/ Tái sử dụng  Incineration/ Chất thải đốt  Landfill/ CHất thải chôn lấp                      NaN                                   NaN  Reuse/Recycle/ Tái sử dụng  Incineration/ Chất thải đốt  Landfill/ CHất thải chôn lấp                      NaN                                   NaN  Reuse/Recycle/ Tái sử dụng  Incineration/ Chất thải đốt  Landfill/ CHất thải chôn lấp                      NaN                                   NaN  Reuse/Recycle/ Tái sử dụng  Incineration/ Chất thải đốt  Landfill/ CHất thải chôn lấp                         NaN                       NaN                        NaN              NaN       NaN  NaN
2   Tiles after kiln, coal slag/ Gạch sau nung, sỉ than,                        0                                 68.78                       68.78                          NaN                           NaN                        0                                 195.2                         NaN                        195.2                           NaN                        0                                     0                         NaN                          NaN                           NaN                        0                                     0                         NaN                          NaN                           NaN                        0                                     0                         NaN                          NaN                           NaN                        0                                     0                         NaN                          NaN                           NaN                        0                                     0                         NaN                          NaN                           NaN                        0                                     0                         NaN                          NaN                           NaN                        0                                     0                         NaN                          NaN                           NaN                        0                                     0                         NaN                          NaN                           NaN                        0                                     0                         NaN                          NaN                           NaN                        0                                     0                         NaN                          NaN                           NaN                           0                       NaN                          0              NaN       NaN  NaN
                                     section  \
0  Hazardous Waste (ton)/ CHẤT THẢI NGUY HẠI
1  Hazardous Waste (ton)/ CHẤT THẢI NGUY HẠI
2  Hazardous Waste (ton)/ CHẤT THẢI NGUY HẠI
3  Hazardous Waste (ton)/ CHẤT THẢI NGUY HẠI
4  Hazardous Waste (ton)/ CHẤT THẢI NGUY HẠI
5  Hazardous Waste (ton)/ CHẤT THẢI NGUY HẠI
6  Hazardous Waste (ton)/ CHẤT THẢI NGUY HẠI
7  Hazardous Waste (ton)/ CHẤT THẢI NGUY HẠI
8  Hazardous Waste (ton)/ CHẤT THẢI NGUY HẠI
9  Hazardous Waste (ton)/ CHẤT THẢI NGUY HẠI

                                   waste_category_en report_month  \
0  Used oil/ Tất cả các loại dầu đã qua sử dụng thải          Jan
1  Used oil/ Tất cả các loại dầu đã qua sử dụng thải          Feb
2  Used oil/ Tất cả các loại dầu đã qua sử dụng thải          Mar
3  Used oil/ Tất cả các loại dầu đã qua sử dụng thải          Apr
4  Used oil/ Tất cả các loại dầu đã qua sử dụng thải          May
5  Used oil/ Tất cả các loại dầu đã qua sử dụng thải          Jun
6  Used oil/ Tất cả các loại dầu đã qua sử dụng thải          Jul
7  Used oil/ Tất cả các loại dầu đã qua sử dụng thải          Aug
8  Used oil/ Tất cả các loại dầu đã qua sử dụng thải          Sep
9  Used oil/ Tất cả các loại dầu đã qua sử dụng thải          Oct

   incoming_stock  waste_generated  reuse_recycle  incineration  landfill
0          5.8526           0.0000            NaN           NaN       NaN
1          5.8526           6.0424            NaN        11.095       NaN
2          0.8000           2.0000            NaN           NaN       NaN
3          2.8000           0.2000            NaN           NaN       NaN
4          3.0000           0.0000            NaN           NaN       NaN
5          3.0000           1.0000            NaN           NaN       NaN
6          4.0000           0.0000            NaN           NaN       NaN
7          4.0000           0.2000            NaN         3.062       NaN
8          1.1380           0.0000            NaN           NaN       NaN
9          1.1380           0.2000            NaN           NaN       NaN

Emission

| STT | Tên cột (Field Name)         | Kiểu dữ liệu   | Ý nghĩa & Ví dụ từ ảnh                                   | Ghi chú                                    |
|-----|------------------------------|---------------|---------------------------------------------------------|--------------------------------------------|
| 1   | stack_no                     | String        | Tên ống khói (Sấy phun 1, Sấy phun 2...)                | Khóa chính để phân loại nguồn thải          |
| 2   | process                      | String        | Quy trình sản xuất liên quan                             |                                            |
| 3   | diameter                     | Float         | Đường kính ống khói (m)                                 | Thông số kỹ thuật cố định                   |
| 4   | sampling_month_year          | String/Date   | Tháng/Năm lấy mẫu (Ví dụ: 2/12/2019)                    | Cột quan trọng để phân biệt các đợt đo      |
| 5   | stack_temperature            | Float         | Nhiệt độ ống khói (°C)                                  |                                            |
| 6   | oxygen_pct                   | Float         | % Oxygen trong khí thải                                  |                                            |
| 7   | gas_velocity                 | Float         | Vận tốc khí (m/s)                                       |                                            |
| 8   | flow_rate                    | Float         | Lưu lượng khí (m3/min)                                  |                                            |
| 9   | dust_emission_actual_o2      | Float         | Kết quả đo bụi thực tế (mg/m3)                          |                                            |
| 10  | dust_emission_rate           | Float         | Tỉ lệ bụi phát thải (kg/hr)                             |                                            |
| 11  | operation_hour               | Float         | Thời gian hoạt động (hr)                                |                                            |
| 12  | dust_emission_total          | Float         | Tổng lượng bụi phát thải (kg)                           | Kết quả của (Cột 10 * Cột 11)              |

In [ ]:
df_emission = pd.read_excel(excel_file, sheet_name='Emission')
print(f"Kích thước dữ liệu gốc: {df_emission.shape}")
display(df_emission.head())

Kích thước dữ liệu gốc: (54, 116)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 106,Unnamed: 107,Unnamed: 108,Unnamed: 109,Unnamed: 110,Unnamed: 111,Unnamed: 112,Unnamed: 113,Unnamed: 114,Unnamed: 115
0,Dust/ Bụi,NaN,NaN,Jan,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,YTD,Q1,Q2,Q3,Q4
1,Stack No.,Process,Diameter/ Đường kính ống khói,Sampling \n(Month/Year),Stack \nTemperature,%Oxygen,Gas Velocity,Flow rate/ Lưu lượng,Dust Emission\nActual O2/ Kết quả đo bụi,Dust Emission \nrate/ Tỉ lệ bụi,...,Flow rate,Dust Emission\nActual O2,Dust Emission \nrate,Operation \nHour,Dust Emission,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,m,MM/YYYY,๐C,%,m/s,m3/min,mg/m3,kg/hr,...,m3/min,mg/m3,kg/hr,hr,kg,NaN,NaN,NaN,NaN,NaN
3,Sấy phun 1,NaN,1.3,2/12/2019,84.3,NaN,NaN,1416.666667,41,3.485,...,1416.666667,43.4,3.689,660,2434.74,NaN,NaN,NaN,NaN,NaN
4,Sấy phun 2,NaN,1.3,2/12/2019,87.1,NaN,NaN,1416.666667,43,3.655,...,1416.666667,42.3,3.5955,436,1567.638,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Tìm index của các dòng chứa chữ 'Stack No.'
stack_no_rows = df_emission[df_emission['Unnamed: 0'].astype(str).str.strip().str.lower() == 'stack no.'].index.tolist()
print("Vị trí các dòng 'Stack No.' tìm thấy:", stack_no_rows)

#Tiến hành cắt bảng
tables = {}
for i in range(len(stack_no_rows)):
    # Dòng bắt đầu của bảng là dòng NGAY TRÊN dòng 'Stack No.'
    start_idx = stack_no_rows[i] - 1
    # Lấy tên bảng
    table_name = str(df_emission.iloc[start_idx, 0]).strip()
    end_idx = stack_no_rows[i+1] - 1 if i + 1 < len(stack_no_rows) else len(df_emission)
    df_sub = df_emission.iloc[start_idx:end_idx].reset_index(drop=True)

    # Dọn dẹp các dòng trống rác cuối bảng
    df_sub = df_sub.dropna(how='all')

    tables[table_name] = df_sub

print(f"\n Đã tách thành công {len(tables)} bảng:")
for name, df in tables.items():
    print(f" - Bảng '{name}': {df.shape[0]} dòng, {df.shape[1]} cột")

    # In nội dung của bảng
    display(df)
    print("\n")

Vị trí các dòng 'Stack No.' tìm thấy: [1, 19, 37]

 Đã tách thành công 3 bảng:
 - Bảng 'Dust/ Bụi': 17 dòng, 116 cột

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 106,Unnamed: 107,Unnamed: 108,Unnamed: 109,Unnamed: 110,Unnamed: 111,Unnamed: 112,Unnamed: 113,Unnamed: 114,Unnamed: 115
0,Dust/ Bụi,NaN,NaN,Jan,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,YTD,Q1,Q2,Q3,Q4
1,Stack No.,Process,Diameter/ Đường kính ống khói,Sampling \n(Month/Year),Stack \nTemperature,%Oxygen,Gas Velocity,Flow rate/ Lưu lượng,Dust Emission\nActual O2/ Kết quả đo bụi,Dust Emission \nrate/ Tỉ lệ bụi,...,Flow rate,Dust Emission\nActual O2,Dust Emission \nrate,Operation \nHour,Dust Emission,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,m,MM/YYYY,๐C,%,m/s,m3/min,mg/m3,kg/hr,...,m3/min,mg/m3,kg/hr,hr,kg,NaN,NaN,NaN,NaN,NaN
3,Sấy phun 1,NaN,1.3,2/12/2019,84.3,NaN,NaN,1416.666667,41,3.485,...,1416.666667,43.4,3.689,660,2434.74,NaN,NaN,NaN,NaN,NaN
4,Sấy phun 2,NaN,1.3,2/12/2019,87.1,NaN,NaN,1416.666667,43,3.655,...,1416.666667,42.3,3.5955,436,1567.638,NaN,NaN,NaN,NaN,NaN
5,"Ống khói lò nung xương 1,2",NaN,0.8,2/12/2019,153.2,NaN,NaN,173.333333,52,0.5408,...,154,45.1,0.416724,744,310.042656,NaN,NaN,NaN,NaN,NaN
6,"Ống khói lò nung xương 3,4",NaN,0.8,2/12/2019,159.1,NaN,NaN,188.333333,53,0.5989,...,158.333333,42.6,0.4047,744,301.0968,NaN,NaN,NaN,NaN,NaN
7,"Ống khói lò nung xương 5,6",NaN,0.8,2/12/2019,146.5,NaN,NaN,175.5,50,0.5265,...,194.166667,43.9,0.511435,744,380.50764,NaN,NaN,NaN,NaN,NaN
8,Ống khói lò nung men số 1,NaN,0.8,29/9/2019,157.3,NaN,NaN,168.666667,51,0.51612,...,178.333333,43.7,0.46759,744,347.88696,NaN,NaN,NaN,NaN,NaN
9,Ống khói lò nung men số 2,NaN,0.8,29/9/2019,124.3,NaN,NaN,141.5,52,0.44148,...,155.666667,44.2,0.412828,744,307.144032,NaN,NaN,NaN,NaN,NaN
10,Ống khói lò nung men số 3,NaN,0.8,29/9/2019,117.7,NaN,NaN,138,52,0.43056,...,202.333333,47.9,0.581506,744,432.640464,NaN,NaN,NaN,NaN,NaN
11,Ống khói lò nung men số 4,NaN,0.8,2/12/2019,150.4,NaN,NaN,177.5,51,0.54315,...,174.166667,46.2,0.48279,624,301.26096,NaN,NaN,NaN,NaN,NaN
12,Ống khói lò nung men số 5,NaN,0.8,2/12/2019,120.1,NaN,NaN,178.333333,52.5,0.56175,...,178.333333,52.5,0.56175,0,0,NaN,NaN,NaN,NaN,NaN
13,Ống khói lò nung men số 6,NaN,0.8,2/12/2019,117.5,NaN,NaN,176,53,0.55968,...,176,45.8,0.483648,744,359.834112,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
15,Total Dust Emission (kg),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,6742.791624,79954.58434,15467.9406,23985.35781,21917.28432,18584.00161
16,Specific Dust Emission (g/ton),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,421.320826,#REF!,#REF!,#REF!,#REF!,#REF!

 - Bảng 'Sox/ Khí Sox': 17 dòng, 116 cột

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 106,Unnamed: 107,Unnamed: 108,Unnamed: 109,Unnamed: 110,Unnamed: 111,Unnamed: 112,Unnamed: 113,Unnamed: 114,Unnamed: 115
0,Sox/ Khí Sox,NaN,NaN,Jan,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,YTD,Q1,Q2,Q3,Q4
1,Stack No.,Process,Diameter,Sampling \n(Month/Year),Stack \nTemperature,%Oxygen,Gas Velocity,Flow rate,SOx Emission\nActual O2,SOx Emission \nrate,...,Flow rate,SOx Emission\nActual O2,SOx Emission \nrate,Operation \nHour,SOx Emission,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,m,MM/YYYY,๐C,%,m/s,m3/min,mg/m3,kg/hr,...,m3/min,mg/m3,kg/hr,hr,kg,NaN,NaN,NaN,NaN,NaN
3,Sấy phun 1,NaN,1.3,2/12/2019,84.3,NaN,NaN,1416.666667,15.72,1.3362,...,1416.666667,94.2,8.007,660,5284.62,NaN,NaN,NaN,NaN,NaN
4,Sấy phun 2,NaN,1.3,2/12/2019,87.1,NaN,NaN,1416.666667,18.34,1.5589,...,1416.666667,94.7,8.0495,436,3509.582,NaN,NaN,NaN,NaN,NaN
5,"Ống khói lò nung xương 1,2",NaN,0.8,2/12/2019,153.2,NaN,NaN,173.333333,83.84,0.871936,...,154,92.4,0.853776,744,635.209344,NaN,NaN,NaN,NaN,NaN
6,"Ống khói lò nung xương 3,4",NaN,0.8,2/12/2019,159.1,NaN,NaN,188.333333,84.71,0.957223,...,158.333333,96.1,0.91295,744,679.2348,NaN,NaN,NaN,NaN,NaN
7,"Ống khói lò nung xương 5,6",NaN,0.8,2/12/2019,146.5,NaN,NaN,175.5,80.19,0.844401,...,194.166667,93.8,1.09277,744,813.02088,NaN,NaN,NaN,NaN,NaN
8,Ống khói lò nung men số 1,NaN,0.8,29/9/2019,157.3,NaN,NaN,168.666667,6.38,0.064566,...,178.333333,96.2,1.02934,744,765.82896,NaN,NaN,NaN,NaN,NaN
9,Ống khói lò nung men số 2,NaN,0.8,29/9/2019,124.3,NaN,NaN,141.5,6.42,0.054506,...,155.666667,97.8,0.913452,744,679.608288,NaN,NaN,NaN,NaN,NaN
10,Ống khói lò nung men số 3,NaN,0.8,29/9/2019,117.7,NaN,NaN,138,8.8,0.072864,...,202.333333,92.9,1.127806,744,839.087664,NaN,NaN,NaN,NaN,NaN
11,Ống khói lò nung men số 4,NaN,0.8,2/12/2019,150.4,NaN,NaN,177.5,91.11,0.970321,...,174.166667,97.1,1.014695,624,633.16968,NaN,NaN,NaN,NaN,NaN
12,Ống khói lò nung men số 5,NaN,0.8,2/12/2019,120.1,NaN,NaN,178.333333,92.18,0.986326,...,178.333333,92.18,0.986326,0,0,NaN,NaN,NaN,NaN,NaN
13,Ống khói lò nung men số 6,NaN,0.8,2/12/2019,117.5,NaN,NaN,176,93.15,0.983664,...,176,95.4,1.007424,744,749.523456,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,...,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
15,Total SOx Emission,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,14588.88507,127854.6071,11285.82036,30400.01477,46002.09951,40166.67242
16,Specific SOx Emission (g/ton),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,911.581055,#REF!,#REF!,#REF!,#REF!,#REF!

 - Bảng 'Nox': 18 dòng, 116 cột

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 106,Unnamed: 107,Unnamed: 108,Unnamed: 109,Unnamed: 110,Unnamed: 111,Unnamed: 112,Unnamed: 113,Unnamed: 114,Unnamed: 115
0,Nox,NaN,NaN,Jan,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,YTD,Q1,Q2,Q3,Q4
1,Stack No.,Process,Diameter,Sampling \n(Month/Year),Stack \nTemperature,%Oxygen,Gas Velocity,Flow rate,NOx Emission\nActual O2,NOx Emission \nrate,...,Flow rate,NOx Emission\nActual O2,NOx Emission \nrate,Operation \nHour,NOx Emission,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,m,MM/YYYY,๐C,%,m/s,m3/min,mg/m3,kg/hr,...,m3/min,mg/m3,kg/hr,hr,kg,NaN,NaN,NaN,NaN,NaN
3,Sấy phun 1,NaN,1.3,2/12/2019,84.3,NaN,NaN,1416.666667,4.4,0.374,...,1416.666667,71.6,6.086,660,4016.76,NaN,NaN,NaN,NaN,NaN
4,Sấy phun 2,NaN,1.3,2/12/2019,87.1,NaN,NaN,1416.666667,4.6,0.391,...,1416.666667,67.9,5.7715,436,2516.374,NaN,NaN,NaN,NaN,NaN
5,"Ống khói lò nung xương 1,2",NaN,0.8,2/12/2019,153.2,NaN,NaN,173.333333,5.1,0.05304,...,154,72.7,0.671748,744,499.780512,NaN,NaN,NaN,NaN,NaN
6,"Ống khói lò nung xương 3,4",NaN,0.8,2/12/2019,159.1,NaN,NaN,188.333333,4.6,0.05198,...,158.333333,68.9,0.65455,744,486.9852,NaN,NaN,NaN,NaN,NaN
7,"Ống khói lò nung xương 5,6",NaN,0.8,2/12/2019,146.5,NaN,NaN,175.5,4.8,0.050544,...,194.166667,70.4,0.82016,744,610.19904,NaN,NaN,NaN,NaN,NaN
8,Ống khói lò nung men số 1,NaN,0.8,29/9/2019,157.3,NaN,NaN,168.666667,5.7,0.057684,...,178.333333,72.4,0.77468,744,576.36192,NaN,NaN,NaN,NaN,NaN
9,Ống khói lò nung men số 2,NaN,0.8,29/9/2019,124.3,NaN,NaN,141.5,5.5,0.046695,...,155.666667,70.7,0.660338,744,491.291472,NaN,NaN,NaN,NaN,NaN
10,Ống khói lò nung men số 3,NaN,0.8,29/9/2019,117.7,NaN,NaN,138,7.2,0.059616,...,202.333333,75.7,0.918998,744,683.734512,NaN,NaN,NaN,NaN,NaN
11,Ống khói lò nung men số 4,NaN,0.8,2/12/2019,150.4,NaN,NaN,177.5,4.5,0.047925,...,174.166667,70.2,0.73359,624,457.76016,NaN,NaN,NaN,NaN,NaN
12,Ống khói lò nung men số 5,NaN,0.8,2/12/2019,120.1,NaN,NaN,178.333333,4.3,0.04601,...,178.333333,4.3,0.04601,0,0,NaN,NaN,NaN,NaN,NaN
13,Ống khói lò nung men số 6,NaN,0.8,2/12/2019,117.5,NaN,NaN,176,5.8,0.061248,...,176,69.8,0.737088,744,548.393472,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,...,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,...,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
16,Total NOx Emission,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,10887.64029,75373.36163,1618.346376,12088.65957,31583.66662,30082.68906
17,Specific NOx Emission (g/ton),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,680.310152,#REF!,#REF!,#REF!,#REF!,#REF!

In [ ]:
import os

# Danh sách tên file
output_filenames = ['Emission_Dust.csv', 'Emission_Nox.csv', 'Emission_Sox.csv']
for df, filename in zip(tables.values(), output_filenames):
    # Xuất ra CSV
    df.to_csv(filename, index=False, encoding='utf-8-sig')
    print(f"Đã xuất thành công file: {filename}")

Đã xuất thành công file: Emission_Dust.csv
Đã xuất thành công file: Emission_Nox.csv
Đã xuất thành công file: Emission_Sox.csv